import React, { useRef } from "react";
import { Modal } from "../Modal/Modal.jsx";
import { Button } from "../Button/Button.jsx";
import "./Modal2FA.css";

/**
 * 2-Factor Authentication modal — illustration, instruction text, a segmented
 * code input, a "having trouble" link, and Cancel / Verify actions. Composes
 * the shared Modal shell. The code input is a controlled string; pass `value`
 * and `onChange(nextCode)`.
 *
 *   <Modal2FA
 *     open={open} onClose={…}
 *     value={code} onChange={setCode}
 *     onVerify={() => …}
 *     length={6}
 *     illustration={<MyArt/>}
 *   />
 */
export function Modal2FA({
  open,
  onClose,
  value = "",
  onChange,
  onVerify,
  onCancel,
  length = 6,
  title = "2-Factor Authentication",
  instruction = "Enter the 6-digit code generated by your Two-factor Authentication (2FA) app.",
  troubleText = "Having trouble with authenticator?",
  onTrouble,
  illustration,
  verifyLabel = "Verify",
  cancelLabel = "Cancel",
  verifyDisabled,
  className = "",
}) {
  const inputs = useRef([]);

  const setDigit = (idx, digit) => {
    const next = value.split("");
    next[idx] = digit;
    const joined = next.join("").slice(0, length);
    onChange && onChange(joined);
  };

  const handleChange = (idx) => (e) => {
    const raw = e.target.value.replace(/\D/g, "");
    if (!raw) {
      setDigit(idx, "");
      return;
    }
    // Support paste of full code.
    if (raw.length > 1) {
      const joined = (value.slice(0, idx) + raw).slice(0, length);
      onChange && onChange(joined);
      const focusIdx = Math.min(idx + raw.length, length - 1);
      inputs.current[focusIdx]?.focus();
      return;
    }
    setDigit(idx, raw);
    if (idx < length - 1) inputs.current[idx + 1]?.focus();
  };

  const handleKeyDown = (idx) => (e) => {
    if (e.key === "Backspace" && !value[idx] && idx > 0) {
      inputs.current[idx - 1]?.focus();
    }
  };

  const handleCancel = () => (onCancel ? onCancel() : onClose && onClose());
  const isVerifyDisabled =
    verifyDisabled !== undefined ? verifyDisabled : value.length < length;

  const footer = (
    <>
      <Button variant="secondary" size="lg" className="2fa__action" onClick={handleCancel}>
        {cancelLabel}
      </Button>
      <Button
        variant="primary"
        size="lg"
        className="2fa__action"
        onClick={onVerify}
        disabled={isVerifyDisabled}
      >
        {verifyLabel}
      </Button>
    </>
  );

  return (
    <Modal
      open={open}
      onClose={onClose}
      size="sm"
      hideClose={false}
      footer={footer}
      className={"2fa " + className}
    >
      <div className="2fa__hero">
        {illustration && <div className="2fa__illustration" aria-hidden="true">{illustration}</div>}
        <h2 className="2fa__title">{title}</h2>
      </div>
      {instruction && <p className="2fa__instruction">{instruction}</p>}
      <div className="2fa__code" role="group" aria-label="Authentication code">
        {Array.from({ length }).map((_, i) => (
          <input
            key={i}
            ref={(el) => (inputs.current[i] = el)}
            className="2fa__digit"
            type="text"
            inputMode="numeric"
            autoComplete={i === 0 ? "one-time-code" : "off"}
            maxLength={1}
            aria-label={`Digit ${i + 1}`}
            value={value[i] ?? ""}
            onChange={handleChange(i)}
            onKeyDown={handleKeyDown(i)}
          />
        ))}
      </div>
      {troubleText && (
        <button type="button" className="2fa__trouble" onClick={onTrouble}>
          {troubleText}
        </button>
      )}
    </Modal>
  );
}
