#!/usr/bin/env python3
"""Enumerate the StraitsX Figma design system via the REST API.

Reads a Figma personal access token from $FIGMA_TOKEN and writes a complete
inventory (pages, published components, component sets, and local variables)
to docs/figma-inventory.json + a human-readable docs/figma-inventory.md.

This backs the Git<->Figma audit/refactor: it produces the authoritative list
of everything in the file so we can diff against src/components and tokens.css.

Usage:
    FIGMA_TOKEN=figd_xxx python3 scripts/figma-enumerate.py
    # optional: FIGMA_FILE_KEY=... to override the default file
"""
import json
import os
import sys
import urllib.request
import urllib.error

FILE_KEY = os.environ.get("FIGMA_FILE_KEY", "pyipgQdAYl4NI0freEfKg4")
TOKEN = os.environ.get("FIGMA_TOKEN", "").strip()
API = "https://api.figma.com/v1"
OUT_JSON = "docs/figma-inventory.json"
OUT_MD = "docs/figma-inventory.md"


def get(path):
    req = urllib.request.Request(API + path, headers={"X-Figma-Token": TOKEN})
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            return json.loads(r.read().decode()), None
    except urllib.error.HTTPError as e:
        return None, f"HTTP {e.code}: {e.read().decode()[:200]}"
    except Exception as e:  # noqa: BLE001
        return None, str(e)


def main():
    if not TOKEN:
        sys.exit("ERROR: set FIGMA_TOKEN (read-only Figma personal access token).")

    inv = {"fileKey": FILE_KEY, "pages": [], "components": [],
           "componentSets": [], "variables": {}, "errors": {}}

    # 1) Pages (canvases) — depth=1 keeps payload small
    data, err = get(f"/files/{FILE_KEY}?depth=1")
    if err:
        inv["errors"]["pages"] = err
    else:
        inv["fileName"] = data.get("name")
        for page in data.get("document", {}).get("children", []):
            inv["pages"].append({"id": page["id"], "name": page.get("name", "")})

    # 2) Published components & component sets
    for kind, key in (("components", "components"), ("componentSets", "component_sets")):
        data, err = get(f"/files/{FILE_KEY}/{key}")
        if err:
            inv["errors"][kind] = err
            continue
        for c in data.get("meta", {}).get(kind if kind == "components" else "component_sets", []):
            inv[kind].append({
                "key": c.get("key"),
                "name": c.get("name"),
                "node_id": c.get("node_id"),
                "containing_frame": (c.get("containing_frame") or {}).get("name"),
                "page": (c.get("containing_frame") or {}).get("pageName"),
                "description": (c.get("description") or "")[:160],
            })

    # 3) Local variables (Enterprise plan only; degrade gracefully)
    data, err = get(f"/files/{FILE_KEY}/variables/local")
    if err:
        inv["errors"]["variables"] = err + " (note: /variables/local needs an Enterprise org token)"
    else:
        m = data.get("meta", {})
        cols = {cid: c.get("name") for cid, c in m.get("variableCollections", {}).items()}
        for vid, v in m.get("variables", {}).items():
            inv["variables"].setdefault(cols.get(v.get("variableCollectionId"), "?"), []).append({
                "name": v.get("name"), "type": v.get("resolvedType"),
            })

    os.makedirs("docs", exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(inv, f, indent=2)

    # Markdown summary
    lines = [f"# Figma Inventory — {inv.get('fileName', FILE_KEY)}",
             f"\nFile key: `{FILE_KEY}`  ·  generated by `scripts/figma-enumerate.py`\n",
             f"## Pages ({len(inv['pages'])})"]
    for p in inv["pages"]:
        lines.append(f"- `{p['id']}` — {p['name']}")
    lines.append(f"\n## Component sets ({len(inv['componentSets'])})")
    for c in sorted(inv["componentSets"], key=lambda x: (x.get("page") or "", x["name"])):
        lines.append(f"- **{c['name']}** — page: {c.get('page')} · `{c['node_id']}`")
    lines.append(f"\n## Components ({len(inv['components'])})")
    for c in sorted(inv["components"], key=lambda x: (x.get("page") or "", x["name"])):
        lines.append(f"- {c['name']} — page: {c.get('page')} · `{c['node_id']}`")
    if inv["variables"]:
        lines.append("\n## Variables")
        for col, vs in inv["variables"].items():
            lines.append(f"\n### {col} ({len(vs)})")
            for v in sorted(vs, key=lambda x: x["name"]):
                lines.append(f"- `{v['name']}` ({v['type']})")
    if inv["errors"]:
        lines.append("\n## Errors / notes")
        for k, v in inv["errors"].items():
            lines.append(f"- **{k}**: {v}")
    with open(OUT_MD, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {OUT_JSON} and {OUT_MD}")
    print(f"pages={len(inv['pages'])} component_sets={len(inv['componentSets'])} "
          f"components={len(inv['components'])} var_collections={len(inv['variables'])}")
    if inv["errors"]:
        print("errors:", json.dumps(inv["errors"], indent=2))


if __name__ == "__main__":
    main()
